# Generated by Django 5.2.6 on 2025-10-11 01:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='学号必须是10-20位数字', regex='^\\d{10,20}$')], verbose_name='学号')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('enrollment_year', models.PositiveIntegerField(blank=True, help_text='例如：2023', null=True, verbose_name='入学年份')),
                ('college', models.CharField(blank=True, max_length=100, verbose_name='学院')),
                ('phone', models.CharField(blank=True, help_text='请输入11位手机号码', max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, help_text='请输入有效的邮箱地址', max_length=254, unique=True, verbose_name='邮箱')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('award_paper', '获奖论文'), ('competition', '竞赛获奖'), ('volunteer', '志愿服务'), ('scholarship', '奖学金'), ('other', '其他')], default='other', max_length=20, verbose_name='加分项类型')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='提交文件')),
                ('self_rating', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='自评加分')),
                ('approved', models.BooleanField(default=False, verbose_name='已审核通过')),
                ('approved_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='审核加分')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile', verbose_name='学生')),
            ],
        ),
    ]
