# Generated by Django 5.2.6 on 2025-10-11 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='系别'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='请输入有效的身份证号', regex='^\\d{17}[\\dXx]$')], verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='political_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='请输入有效的邮箱地址', max_length=254, verbose_name='邮箱'),
        ),
    ]
