# Generated by Django 5.2.6 on 2025-10-11 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_department_studentprofile_ethnicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='驳回理由'),
        ),
        migrations.AddField(
            model_name='submission',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='已驳回'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='学号必须是8-20位数字', regex='^\\d{8,20}$')], verbose_name='学号'),
        ),
    ]
