# Generated by Django 5.2.6 on 2025-10-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_submission_reject_reason_submission_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='学业成绩'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='material_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='材料加分'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='score_ratio',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='例如：0.7表示学业成绩占70%', max_digits=3, verbose_name='学业成绩换算比例'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='总分'),
        ),
    ]
