# Generated by Django 5.2.6 on 2025-10-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_academic_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='academic_score',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='material_score',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='score_ratio',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_comprehensive_ratio',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=3, verbose_name='学业综合成绩权重'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_comprehensive_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='学业综合成绩'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_expertise_ratio',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3, verbose_name='学术专长成绩权重'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_expertise_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='学术专长成绩'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='comprehensive_performance_ratio',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3, verbose_name='综合表现成绩权重'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='comprehensive_performance_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='综合表现成绩'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='总成绩'),
        ),
    ]
