# Generated by Django 5.2.6 on 2025-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentprofile_academic_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='加分项目名称')),
                ('description', models.TextField(verbose_name='加分标准说明')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='加分分值')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('rule_type', models.CharField(choices=[('student-competition', '学业竞赛'), ('research-achievement', '科研成果'), ('innovation-entrepreneurship', '创新创业训练'), ('comprehensive-performance', '综合表现加分')], max_length=50, verbose_name='规则分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '加分规则',
                'verbose_name_plural': '加分规则',
            },
        ),
    ]
