# Generated by Django 5.2.6 on 2025-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, choices=[('info', '信息学院'), ('other', '其他')], default='other', max_length=100, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('award_paper', '科研成果'), ('competition', '学业竞赛'), ('volunteer', '创新创业训练'), ('scholarship', '综合表现加分'), ('other', '其他')], default='other', max_length=20, verbose_name='加分项类型'),
        ),
    ]
