# Generated by Django 5.2.6 on 2025-12-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0007_alter_counselorprofile_college'),
        ('students', '0008_alter_studentprofile_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='counselors.counselorprofile'),
        ),
    ]
