# Generated by Django 5.2.6 on 2025-12-23 13:11

import django.db.models.deletion
from django.db import migrations, models


def add_initial_categories(apps, schema_editor):
    SubmissionCategory = apps.get_model('students', 'SubmissionCategory')

    # 1. 科研成果（award_paper）
    SubmissionCategory.objects.create(
        group='award_paper',
        name='A类论文发表',
        description='SCI/SSCI收录论文（第一作者）',
        default_score=10.0,
        max_score=15.0
    )
    SubmissionCategory.objects.create(
        group='award_paper',
        name='B类论文发表',
        description='EI收录论文（第一作者）',
        default_score=8.0,
        max_score=10.0
    )
    SubmissionCategory.objects.create(
        group='award_paper',
        name='国家发明专利授权',
        description='发明人排名前3',
        default_score=8.0,
        max_score=10.0
    )
    SubmissionCategory.objects.create(
        group='award_paper',
        name='省级优秀毕业论文',
        description='本科或硕士阶段获得',
        default_score=5.0,
        max_score=8.0
    )
    SubmissionCategory.objects.create(
        group='award_paper',
        name='其他',
        description='其他科研成果',
        default_score=0.0,
        max_score=100.0
    )

    # 2. 学业竞赛（competition）
    SubmissionCategory.objects.create(
        group='competition',
        name='A+类国家级竞赛',
        description='全国大学生数学建模竞赛一等奖等',
        default_score=15.0,
        max_score=20.0
    )
    SubmissionCategory.objects.create(
        group='competition',
        name='A类国家级竞赛',
        description='全国大学生电子设计竞赛二等奖等',
        default_score=10.0,
        max_score=15.0
    )
    SubmissionCategory.objects.create(
        group='competition',
        name='A类省级竞赛',
        description='省级数学建模竞赛一等奖',
        default_score=8.0,
        max_score=12.0
    )
    SubmissionCategory.objects.create(
        group='competition',
        name='B类省级竞赛',
        description='省级计算机设计大赛二等奖',
        default_score=5.0,
        max_score=8.0
    )
    SubmissionCategory.objects.create(
        group='competition',
        name='其他',
        description='其他学业竞赛',
        default_score=0.0,
        max_score=100.0
    )

    # 3. 创新创业训练（volunteer）
    SubmissionCategory.objects.create(
        group='volunteer',
        name='国家级大创项目',
        description='负责人，项目结题优秀',
        default_score=10.0,
        max_score=12.0
    )
    SubmissionCategory.objects.create(
        group='volunteer',
        name='省级大创项目',
        description='核心成员（前2），项目结题',
        default_score=6.0,
        max_score=8.0
    )
    SubmissionCategory.objects.create(
        group='volunteer',
        name='创业大赛国家级',
        description='互联网+创新创业大赛金奖',
        default_score=12.0,
        max_score=15.0
    )
    SubmissionCategory.objects.create(
        group='volunteer',
        name='创业大赛省级',
        description='挑战杯创业计划竞赛银奖',
        default_score=8.0,
        max_score=10.0
    )
    SubmissionCategory.objects.create(
        group='volunteer',
        name='其他',
        description='其他创新创业训练',
        default_score=0.0,
        max_score=100.0
    )

    # 4. 综合表现加分（scholarship）
    SubmissionCategory.objects.create(
        group='scholarship',
        name='国家奖学金',
        description='当学年获得',
        default_score=10.0,
        max_score=10.0
    )
    SubmissionCategory.objects.create(
        group='scholarship',
        name='省级优秀学生',
        description='省级教育厅评选',
        default_score=8.0,
        max_score=8.0
    )
    SubmissionCategory.objects.create(
        group='scholarship',
        name='校级优秀干部',
        description='连续两年获得',
        default_score=5.0,
        max_score=6.0
    )
    SubmissionCategory.objects.create(
        group='scholarship',
        name='志愿服务时长',
        description='累计超过200小时',
        default_score=3.0,
        max_score=5.0
    )
    SubmissionCategory.objects.create(
        group='scholarship',
        name='其他',
        description='其他综合表现加分',
        default_score=0.0,
        max_score=5.0
    )

    # 5. 其他（other）
    SubmissionCategory.objects.create(
        group='other',
        name='其他',
        description='其他',
        default_score=0.0,
        max_score=100.0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_submission_reviewer'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories),
        migrations.CreateModel(
            name='SubmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('award_paper', '科研成果'), ('competition', '学业竞赛'), ('volunteer', '创新创业训练'), ('scholarship', '综合表现加分'), ('other', '其他')], max_length=20, verbose_name='大类')),
                ('name', models.CharField(max_length=100, verbose_name='小类名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('default_score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='预设分值')),
                ('max_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最大分值')),
            ],
            options={
                'verbose_name': '加分项细分分类',
                'verbose_name_plural': '加分项细分分类',
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='students.submissioncategory', verbose_name='加分项细分分类'),
        ),
    ]
