# Generated by Django 5.2.6 on 2025-11-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('student-competition', '学生竞赛'), ('research-achievement', '科研成果'), ('innovation-entrepreneurship', '创新创业训练'), ('comprehensive-performance', '综合表现加分')], max_length=50, verbose_name='规则类型')),
                ('description', models.TextField(verbose_name='规则描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rules', to='counselors.counselorprofile')),
            ],
            options={
                'verbose_name': '加分规则',
                'verbose_name_plural': '加分规则',
            },
        ),
    ]
