# Generated by Django 5.2.6 on 2025-11-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0002_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='created_by',
        ),
        migrations.AddField(
            model_name='rule',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='加分项目名称'),
        ),
        migrations.AddField(
            model_name='rule',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='rule',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='加分分值'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(verbose_name='加分标准说明'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('student-competition', '学业竞赛'), ('research-achievement', '科研成果'), ('innovation-entrepreneurship', '创新创业训练'), ('comprehensive-performance', '综合表现加分')], max_length=50, verbose_name='规则分类'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
