# Generated by Django 5.2.6 on 2025-11-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0003_remove_rule_created_by_rule_item_name_rule_remark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
