# Generated by Django 5.2.6 on 2025-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0004_delete_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='grade',
            field=models.CharField(blank=True, help_text='例如：2021级、2022级', max_length=20, verbose_name='负责年级'),
        ),
    ]
