# Generated by Django 5.2.6 on 2025-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0005_counselorprofile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorprofile',
            name='college',
            field=models.CharField(blank=True, default='无', max_length=100, verbose_name='所属学院'),
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='grade',
            field=models.CharField(blank=True, default='无', max_length=20, verbose_name='负责年级'),
        ),
    ]
