# Generated by Django 5.2.6 on 2025-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0006_alter_counselorprofile_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorprofile',
            name='college',
            field=models.CharField(blank=True, choices=[('info', '信息学院'), ('other', '其他')], default='other', max_length=100, verbose_name='所属学院'),
        ),
    ]
